
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int TD = 30;
  public static final int H6 = 73;
  public static final int H5 = 71;
  public static final int H4 = 69;
  public static final int H3 = 67;
  public static final int H2 = 65;
  public static final int FRAME = 14;
  public static final int H1 = 63;
  public static final int ESUB = 56;
  public static final int ETFOOT = 37;
  public static final int TABLE = 24;
  public static final int ELI = 46;
  public static final int ESELECT = 21;
  public static final int SUP = 57;
  public static final int EFONT = 60;
  public static final int SUB = 55;
  public static final int FONT = 59;
  public static final int TFOOT = 36;
  public static final int FRAMESET = 12;
  public static final int LI = 45;
  public static final int CENTER = 61;
  public static final int TEXT = 9;
  public static final int EHTML = 3;
  public static final int HTML = 2;
  public static final int EU = 52;
  public static final int EP = 76;
  public static final int EI = 50;
  public static final int SELECT = 20;
  public static final int ESMALL = 54;
  public static final int EB = 48;
  public static final int EA = 40;
  public static final int NOFRAMES = 15;
  public static final int INPUT = 19;
  public static final int U = 51;
  public static final int P = 75;
  public static final int ETITLE = 7;
  public static final int EFRAMESET = 13;
  public static final int SMALL = 53;
  public static final int EOL = 44;
  public static final int I = 49;
  public static final int EOPTION = 23;
  public static final int EFORM = 18;
  public static final int EUL = 42;
  public static final int FORM = 17;
  public static final int LINK = 8;
  public static final int EOF = 0;
  public static final int B = 47;
  public static final int A = 39;
  public static final int EBODY = 11;
  public static final int BODY = 10;
  public static final int TITLE = 6;
  public static final int ETBODY = 35;
  public static final int error = 1;
  public static final int ETR = 27;
  public static final int OL = 43;
  public static final int EHEAD = 5;
  public static final int UL = 41;
  public static final int HEAD = 4;
  public static final int ENOFRAMES = 16;
  public static final int ETHEAD = 33;
  public static final int ETH = 29;
  public static final int IMG = 38;
  public static final int ETD = 31;
  public static final int BR = 78;
  public static final int EH6 = 74;
  public static final int EH5 = 72;
  public static final int EH4 = 70;
  public static final int EH3 = 68;
  public static final int HR = 77;
  public static final int EH2 = 66;
  public static final int EH1 = 64;
  public static final int OPTION = 22;
  public static final int TBODY = 34;
  public static final int ECENTER = 62;
  public static final int TR = 26;
  public static final int ETABLE = 25;
  public static final int THEAD = 32;
  public static final int ESUP = 58;
  public static final int TH = 28;

  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HTML",
  "EHTML",
  "HEAD",
  "EHEAD",
  "TITLE",
  "ETITLE",
  "LINK",
  "TEXT",
  "BODY",
  "EBODY",
  "FRAMESET",
  "EFRAMESET",
  "FRAME",
  "NOFRAMES",
  "ENOFRAMES",
  "FORM",
  "EFORM",
  "INPUT",
  "SELECT",
  "ESELECT",
  "OPTION",
  "EOPTION",
  "TABLE",
  "ETABLE",
  "TR",
  "ETR",
  "TH",
  "ETH",
  "TD",
  "ETD",
  "THEAD",
  "ETHEAD",
  "TBODY",
  "ETBODY",
  "TFOOT",
  "ETFOOT",
  "IMG",
  "A",
  "EA",
  "UL",
  "EUL",
  "OL",
  "EOL",
  "LI",
  "ELI",
  "B",
  "EB",
  "I",
  "EI",
  "U",
  "EU",
  "SMALL",
  "ESMALL",
  "SUB",
  "ESUB",
  "SUP",
  "ESUP",
  "FONT",
  "EFONT",
  "CENTER",
  "ECENTER",
  "H1",
  "EH1",
  "H2",
  "EH2",
  "H3",
  "EH3",
  "H4",
  "EH4",
  "H5",
  "EH5",
  "H6",
  "EH6",
  "P",
  "EP",
  "HR",
  "BR"
  };
}

